In [27]:
import pickle
import os
import numpy as np
import pandas as pd

In [30]:
os.makedirs('models', exist_ok=True)

# Save models
pickle.dump(ohe_sex, open('models/ohe_sex.pkl','wb'))
pickle.dump(ohe_embarked, open('models/ohe_embarked.pkl','wb'))
pickle.dump(clf, open('models/clf.pkl','wb'))

In [31]:

# Assume user input
# Pclass/gender/age/SibSp/Parch/Fare/Embarked
test_input = np.array([2, 'male', 31.0, 0, 0, 10.5, 'S'],dtype=object).reshape(1,7)

In [32]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [35]:
import warnings
warnings.filterwarnings('ignore', message='X does not have valid feature names')

test_input_sex = ohe_sex.transform(test_input[:, 1].reshape(1, 1))


In [36]:
test_input_sex


array([[0., 1.]])

In [37]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))


In [38]:
test_input_embarked


array([[0., 0., 1.]])

In [39]:
test_input_age = test_input[:,2].reshape(1,1)


In [40]:
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)


In [41]:
test_input_transformed.shape


(1, 10)

In [42]:
clf.predict(test_input_transformed)


array([1])